### ISSUE TITLE
[Effective Java] Item 17. "인스턴스를 재활용한다"를 정확히 모르겠습니다 ㅠ

### ISSUE THREAD

**Issue by taxol1203** [kjsu0209/JavaBook#10]
질문이 많은 학생임니다.  
108p. 8번째 줄에서 "불변 클래스이면 최대한 재활용"이라고 되어있습니다.  
불변 클래스이므로 상수화 하여 각 객체를 사용하는 것은 알겠는데, 아래의 예시를 보면 new를 통하여 3개의 Complex 객체를 생성하였습니다.  
그렇다면 Heap 영역에 3개의 Complex 인스턴스가 생긴것 같은데,, 아래 예시는 하나의 Complex()로 3개를 재활용하였다고 말하고 있는 것 같습니다.  
```java
public static final Complex Zero = new Complex(0,0);    // public static final로 상수화!
public static final Complex One  = new Complex(1,0);
public static final Complex IIII = new Complex(0,1);
```
인스턴스 재활용이란 것이 정확이 무엇을 뜻하는 걸까요??

**Comment by kjsu0209** [comment]
```
public final Complex{
    public static final Complex Zero = new Complex(0,0);    // public static final로 상수화!
    public static final Complex One  = new Complex(1,0);
    public static final Complex IIII = new Complex(0,1);
}
```
세 인스턴스 모두 Complex 클래스의 static final 멤버 변수이니 컴파일할 때 만들어집니다. 예를 들어 Complex(0,0) 객체가 필요할 때마다 이미 만들어진 인스턴스인 Complex.Zero를 쓰면 돼서 인스턴스 재활용이라고 합니다.

**Comment by jth2747** [comment]
불변 클래스의 장점으로는 멀티 스레드 환경에서 동기화 처리 없이 **객체를 공유**할 수 있다고 합니다. 클라이언트가 특정 상수를 사용하고 싶을 때, 올려주신 코드에서 그 상수가 선언이 되어있다면 동기화 처리 없이 객체를 공유할 수 있습니다. 그것을 인스턴스 재활용이라고 합니다.
