### ISSUE TITLE
[Effective Java] Item 20. 단순 구현(simple implementation)

### ISSUE THREAD

**Issue by kjsu0209** [kjsu0209/JavaBook#11]
135p에서 ```AbstactMap.SimpleEntry```가 인터페이스를 구현한 골격 구현(단순 구현)이지만 추상 클래스가 아니라고 합니다.
그러면 단순 구현은 일반 클래스로 인터페이스를 구현하는 걸 말하나요? 아니면 인터페이스에서 디폴트 메서드만으로도 구현이 가능할 때 단순 구현이라고 하나요?

**Comment by jth2747** [comment]
AbstractMap.SimpleEntry API를 잘 살펴보시면, java.util.Map.Entry에서 comparingByKey, comparingByKey, comparingByValue, comparingByValue를 각각 상속받아서 구현하고 있습니다. java.util.Map.Entry를 확인해보시면 각 4개의 메소드가 default 메소드인 것을 알 수 있습니다. 이것과 책에서 단순 구현의 개념을 참고해보면, AbstractMap.SimpleEntry가 java.util.Map.Entry를 추상 클래스로 두지 않으며 디폴트 메서드만으로도 정말 **단순하게** 구현이 가능한 것을 단순 구현이라고 하는 것 같습니다.

**Comment by kjsu0209** [comment]
문서 보니까 SimpleEntry가 AbstractMap을 추상 클래스로 두는데 AbstractMap만 골격 구현이라고 이해하면 될까요?

**Comment by jth2747** [comment]
네, AbstractMap은 Map 인터페이스의 골격 구현을 제공한다고 되어 있습니다. AbstractMap은 Map의 골격 구현이라고 보고 SimpleEntry는 AbstractMap을 추상 클래스로 두나 Map.Entry를 추상 클래스로 두지 않고 Map.entry의 디폴트 메서드들만을 단순 구현한 것 같습니다..
