### ISSUE TITLE
[Effective Java] Item 26. 와일드카드

### ISSUE THREAD

**Issue by kjsu0209** [kjsu0209/JavaBook#14]
책 158p 2번째 문단에서 ```비한정적 와일드카드 <?>를 붙이면 null 외에는 어떤 원소도 넣을 수 없다```고 되어 있는데    
같은 페이지 1번째 문단에서는 ```Set<?>은 어떤 타입이라도 담을 수 있는 범용적인 Set 타입```이라고 합니다.  

와일드카드의 정확한 정의가 무엇일까요,,

**Comment by taxol1203** [comment]
아하! 그렇다면 비한정적 타입은 불공변인 제네릭 타입의 계층 관계를 나타낼 수 있게 해주는 거군요.
오직 그런 용도로만 사용되니, 다른 데이터가 못들어 오게 하는거구요.
제가 이해한게 맞다면, 저도 의문이었는데 한번에 이해됐습니다! 감사합니다
