### ISSUE TITLE
[Effective Java] Item 28. 제네릭 타입과 가변인수 메서드

### ISSUE THREAD

**Issue by taxol1203** [kjsu0209/JavaBook#15]
166p. 3번째 문단에서 ```제네릭 타입과 가변 인수 메서드를 함께 쓰면 경고가 발생한다``` 라고 되어있습니다.  
정확히 어떤 경우를 뜻하는 걸까요? 메서드의 가변 인수에 제네릭 타입을 넣어 사용한다는 뜻일까요?

**Comment by kjsu0209** [comment]
가변인수 메서드를 호출하면 가장 먼저 인수의 개수와 길이가 같은 배열을 만들고 인수들을 배열에 저장하여 가변인수 메서드에 건네준다고 합니다. [Item 53]   
Item 28에서 ```제네릭은 자신의 원소 타입을 담은 배열을 반환하는 게 일반적으로 불가능하다```고 나오는데, ```가변인수 메서드는 인수의 원소 타입을 담은 배열을 반환```하기 때문에 경고가 발생한다고 보면 될 것 같습니다.
