### ISSUE TITLE
[Effective Java] Item 31. PECS에 나오는 생산자와 소비자 의미

### ISSUE THREAD

**Issue by kjsu0209** [kjsu0209/JavaBook#17]
> 펙스(PECS): producer-extends, consumer-super

184p에 한정적 와일드카드 타입을 선택할 때 쓰는 공식이 나오는데, 여기서 나오는 생산자와 소비자 의미가 구체적으로 무엇인지 궁금합니다. 생산자는 팩터리고 소비자는 getter라고 생각하면 될까요?

**Comment by taxol1203** [comment]
저도 그렇게 이해하였습니다!  
코드 31-2를 보면, 생산자는 외부 Integer를 Stack의 내부 인스턴스인 Number[]에 넘겨주고,
코드 31-4에선 object 타입에 Stack의 Number 타입 데이터를 넘겨준다고 생각하였습니다.
