### ISSUE TITLE
[Effective Java] Item 31. 목표 타이핑(target typing)

### ISSUE THREAD

**Issue by kjsu0209** [kjsu0209/JavaBook#18]
자바 8부터 목표 타이핑이 지원된다는데 목표 타이핑이 뭘까요 👀

**Comment by jth2747** [comment]
계산식의 결과 자료형이 long형이기 때문에 컴파일러가 계산식을 계산식의 결과 자료형으로 자동 변환하여 연산을 수행하는 기능을 target typing이라고 합니다. 자바는 기본 자료형 연산에 target typing을 지원하지 않는데, 자바8부터 람다식에 target typing을 지원한다고 합니다
