### ISSUE TITLE
[Effective Java] Item 29. 제네릭 타입의 타입 매개변수에 기본 타입이 들어갈 수 없는 이유??

### ISSUE THREAD

**Issue by taxol1203** [kjsu0209/JavaBook#19]
예전 부터 궁금했던 것인데, 174p.  두번째 문단에서, int와 duble과 같은 기본 타입은 타입 매개변수로 사용이 불가하다고 합니다.  
Boxing Class로 우회하여 사용은 가능한다고 하는데 왜 사용하지 못할까요?

**Comment by kjsu0209** [comment]
제네릭은 클래스와 인터페이스만 적용되기 때문에 자바 기본 타입(Primitive Type)은 사용할 수 없습니다.  

[참고](https://madplay.github.io/post/java-generic-advanced)
