### ISSUE TITLE
9페이지 첫번째 줄

### ISSUE THREAD

**Issue by jth2747** [kjsu0209/JavaBook#2]
입력 매개변수들의 순서를 다르게 한 생성자를 새로 추가하는 식.. 이 저희가 수업 때 썼던
그 방식인가요?

**Comment by taxol1203** [comment]
네 저희가 배운 생성자 오버로딩의 방법이라고 할 수 있습니다. 
첫번째 줄에 나온 **하나의 시그니처** 또한 말씀하신 매개변수의 개수와 타입, 순서를 나타내는 것이며, 해당하는 정보는 
[메서드 시그니처](https://gbsb.tistory.com/218)에서 참고하시면 될 것 같습니다!
