### ISSUE TITLE
[Effective Java] Item 26. 비한정적 와일드카드 타입의 의의?

### ISSUE THREAD

**Issue by daebalprime** [kjsu0209/JavaBook#21]
비한정적 와일드카드 타입을 쓰는 의의는 어떤 것이 있을까요?
그 어떠한 조작도 불가능하면 굳이 파라미터로 넘겨줘야 하는 생각도 드네요

개인 사정으로 좀 늦게 시작했습니다.
월요일 발표에 지장없도록 주말간 달려보겠습니다.

**Comment by daebalprime** [comment]
https://newstars.tistory.com/33?fbclid=IwAR2PAaKqE6ezAOE2zg-ygO_LUMIrDt6mF_q6o7G9tz5vw0TEoxWs7kgLC7s

**Comment by kjsu0209** [comment]
링크도 좋지만 설명과 함께 올려주시면 더 좋을 것 같습니다~ :smile:
