### ISSUE TITLE
[Effective Java] Item 26. 클래스 리터럴에 대한 이해

### ISSUE THREAD

**Issue by daebalprime** [kjsu0209/JavaBook#22]
클래스 리터럴로 얻어낼 수 있는 Class type으로 어떤 일을 할 수 있나요?
한국어로 된 블로그나 문서에는 이 내용을 찾을 수가 없네요.

**Comment by kjsu0209** [comment]
클래스 리터럴(Class Literal)은 Class(클래스) Class를 의미하며, Class의 인스턴스가 클래스나 인터페이스임을 나타냅니다. JDK 5부터 java.lang.Class가 제네릭이 됐다고 합니다.
```Class type```이 아마 타입 토큰인 것 같은데, 타입 토큰은 클래스 리터럴을 타입을 나타내는 토큰으로 쓰는 것이라고 합니다.  

아래 예시 코드에서는 EmpInfo.class 클래스 리터럴을 타입 토큰으로 해서 select 메서드의 매개변수로 넘깁니다. 
그러면 select 메서드의 <T> 변수에 EmpInfo.class의 인스턴스가 들어갈 수 있는지 런타임에서 검사할 수 있어 더 안전하게 제네릭 클래스의 타입을 정할 수 있습니다.
```
Collection<EmpInfo> 
    emps = sqlUtility.select(EmpInfo.class, "select * from emps");
...
public static <T> Collection<T> select(Class<T> c, String sqlStatement) { 
    Collection<T> result = new ArrayList<T>();
    /* Run sql query using jdbc. */
    for (/* Iterate over jdbc results. */ ) { 
        T item = c.newInstance(); 
        /* Use reflection and set all of item's
         * fields from sql results. 
         */  
        result.add(item);
    } 
    return result; 
} 
```

그래서 타입 토큰을 쓰면 제네릭에서 타입을 명시적으로 지정하지 않고도 타입 안전성을 확보할 수 있습니다. 

[참고 1 - 클래스 리터럴](https://stackoverflow.com/questions/2160788/what-is-a-class-literal-in-java)
[참고 2 - 타입 토큰](https://homoefficio.github.io/2016/11/30/%ED%81%B4%EB%9E%98%EC%8A%A4-%EB%A6%AC%ED%84%B0%EB%9F%B4-%ED%83%80%EC%9E%85-%ED%86%A0%ED%81%B0-%EC%88%98%ED%8D%BC-%ED%83%80%EC%9E%85-%ED%86%A0%ED%81%B0/)
[참고 3 - 런타임에서 클래스 리터럴 활용사례 - 타입 토큰](https://docs.oracle.com/javase/tutorial/extra/generics/literals.html)
