### ISSUE TITLE
[Effective Java] Item 34. enum과 컴파일 관련 질문

### ISSUE THREAD

**Issue by daebalprime** [kjsu0209/JavaBook#23]
> 210p 공개되는 것이 오직 필드의 이름뿐이라, 정수 열거 패턴ㄷ과 달리 상수 값이 클라이언트로 컴파일되어 각인되지 않기 때문이다

라고 하는데, 
1. 그렇다면 필드의 이름과 매칭되는 상수값은 어디에 저장되나요?
2. 정수 열거 타입에서는 값을 바꾸게 되면 컴파일을 새로 하여야 한다고 했습니다. 새로운 상수가 추가되거나 순서가 바뀌는 것도 enum 클래스의 변화를 가져올텐데 왜 컴파일을 하지 않아도 될까요

**Comment by daebalprime** [comment]
https://stackoverflow.com/questions/17592584/enum-requires-no-recompilation-of-its-clients-how
자문자답입니다. 아직 자바의 컴파일러의 동작이 잘 이해가 되지는 않지만, 전체 코드를 컴파일 할 때 다른 클래스에서 해당 상수를 참조할 경우 변수 대신 변수의 값인 상수를 딱 박아버리는 것 같습니다.

**Comment by kjsu0209** [comment]
추가 설명 남깁니다 😃 
enum 클래스의 상수는 각각 싱글턴 인스턴스 개념입니다. 그래서 값을 바꾸더라도 클래스가 아닌 인스턴스에 접근하기 때문에 재컴파일을 하지 않아도 된다고 이해하면 될 것 같습니다.
