### ISSUE TITLE
[Effective Java] Item 37. 스트림 API

### ISSUE THREAD

**Issue by kjsu0209** [kjsu0209/JavaBook#25]
228p 코드 37-3에 사용된 ```스트림```이 뭘까요?
```
System.out.println(Arrays.stream(garden)
    .collect(groupingBy(p -> p.lifeCycle)));
```
garden 배열을 돌면서 나오는 요소를 p.lifeCycle로 매핑해서 리턴한다고 이해하면 될까요🤔

**Comment by daebalprime** [comment]
추후 다뤄질 아이템이기에 나중에 보려고 생각했었습니다...만
https://futurecreator.github.io/2018/08/26/java-8-streams/ 링크 설명이 친절합니다.

>자바 8에서 추가한 스트림(Streams)은 람다를 활용할 수 있는 기술 중 하나입니다. 자바 8 이전에는 배열 또는 컬렉션 인스턴스를 다루는 방법은 for 또는 foreach 문을 돌면서 요소 하나씩을 꺼내서 다루는 방법이었습니다. 간단한 경우라면 상관없지만 로직이 복잡해질수록 코드의 양이 많아져 여러 로직이 섞이게 되고, 메소드를 나눌 경우 루프를 여러 번 도는 경우가 발생합니다.
