### ISSUE TITLE
[Effective Java] Item 39. Marker annotation 관련

### ISSUE THREAD

**Issue by daebalprime** [kjsu0209/JavaBook#26]
239p 코드 39-2에서, 
m5()가 정적 메서드가 아닌데 @Test를 붙일 때, 39-3 코드에서 해당 메서드가 실패하는 이유는 무엇인가요?
너무 설명이 불친절합니다... 책 저자 내일 버스 정류장 코앞에서 타야하는 버스 놓치길 기원...

**Comment by taxol1203** [comment]
우선 코드 39-1에 보시면,
```java
import java.lang.annotation.*;

// 테스트 메서드임을 선언하는 애너테이션
// 매개변수 없는 정적 메서드 전용이다.
@Retention(RetentionPolicy.RUNTIME) // @Mad가 런타임에도 유지되어야 한다는 뜻
@Target(ElementType.METHOD) // @Test가 메서드 선언에서만 사용돼야 한다는 뜻
public @interface Test {
	String hi = "hi";
}
```
라고 주석에 "매개변수 없는 정적 메서드 전용이다"라고 되어있습니다.  
한마디로, 이 애너테이션을 적용하려는 메서드들은 반드시 정적 메서드가 되어야 한다는 뜻이지요.  
이에 따라 238p의 두번째 문단을 보시면,  
```
앞 코드의 메서드 주석에는 "매개변수 없는 정적 메서드 전용이다"라고 쓰여져있다.  
이 제약을 컴파일러가 강제할 수 있으면 좋겠지만, 그렇게 하려면 적절한 애너테이션 처리기를 직접 구현해야 한다.
```
라고 명시되어있습니다.  

이제 코드 39-3의 마커 애너테이션을 처리하는 프로그램을 보시면, `method.invoke(null)`이 있습니다.
```java
try {
    method.invoke(null);    // 마킹된 메서드가 static인지 확인하는 함수
    passedCount++;
} catch (InvocationTargetException itException) {
    Throwable ex = itException.getCause();
    System.out.println(method + " 실패: " + ex);
} catch (Exception e) {
    System.out.println("잘못 사용한 @Test: " + method);
}
```
디버깅으로 해당 클래스를 실행 해 보시면, m5()가 method에 들어왔을 때 invoke(null)에서 catch되어 잘 못 사용된 메서드라고 나옵니다.

따라서 제 생각은, `method.invoke(null)`을 통해 Test 애너테이션을 구현 할때, 정적 메서드만 받는 애너테이션 처리기를 만든 것으로 생각 됩니다.

**Comment by daebalprime** [comment]
@taxol1203 
링크 걸어주신 스택 오버플로우를 확인했습니다.
> If the underlying method is static, then the specified obj argument is ignored. It may be null.

invoke(null)이 static 메서드를 위한 것이고 컴파일러 단에서는 잡지 못하는 문제였던 것 같네요.
명확하게 이해되었습니다.
