### ISSUE TITLE
[Effective Java] Item 42. 비교자 생성 메서드?

### ISSUE THREAD

**Issue by kjsu0209** [kjsu0209/JavaBook#28]
255p 2번째 문단에 ```비교자 생성 메서드```와 코드가 나오는데 코드가 너무 간결해서 이해하기 어려운 것 같습니다..

```
Collections.sort(words, comparingInt(String::length));
```
인자로 이중 콜론 연산 결과를 받고 Comparator를 반환하면 ```비교자 생성 메서드```인가요?

**Comment by daebalprime** [comment]
아마 뒷 아이템들을 공부하면서 의미를 깨달으셨겠지만, 정리 겸 설명드리자면 comparingInt는 Integer.compare()의 메서드 참조형 표현입니다. 
(o1,o2)->compareInt(o1.length() , o2.length());와 같은 역할을 하신다고 보면 되겠습니다.

우리가 람다를 쓰지 않고 익명 클래스로 Comparator 인스턴스를 인자로 넘기는걸 생각해 봤을 때, 함수 표현식의 클래스 생성자 메서드 참조 유형을 따른다고 보시면 되고, 그렇기에 비교자 (인스턴스)를 생성하는 메서드라고 해서 비교자 생성 메서드라고 하는 것 같습니다.
