### ISSUE TITLE
[Effective Java] Item 42. DoubleBinaryOperator

### ISSUE THREAD

**Issue by taxol1203** [kjsu0209/JavaBook#29]
코드 42-4에서 DoubleBinaryOperator의 역할이 정확하게 잘 이해가 가지 않네요,  

Operation 클래스의 apply() 메서드는 DoubleBinaryOperator의 인스턴스 op를 호출하여 계산하고 리턴하는데,  
이 op와 람다 함수의 관계를 모르겠습니다.  

혹시 이 Enum 클래스의 동작 과정과 함께 설명 부탁드려도 될까요?

```java
public class item42_Operation {
	enum Operation {
	    PLUS("+", (x, y) -> x + y),
	    MINUS("-", (x, y) -> x - y),
	    TIMES("*", (x, y) -> x * y),
	    DIVIDE("/", (x, y) -> x / y);

	    private final String symbol;
	    private final DoubleBinaryOperator op;

	    Operation(String symbol, DoubleBinaryOperator op) {
	        this.symbol = symbol;
	        this.op = op;
	    }

	    @Override
	    public String toString() { return symbol; }

	    public double apply(double x, double y) {
	        return op.applyAsDouble(x, y);  // ???
	    }
	}

    public static void main(String[] args) {
        // 사용은 아래와 같이
        double num = Operation.PLUS.apply(2, 3);
        System.out.println(num);
	}
}
```

**Comment by daebalprime** [comment]
Enum의 각 상수는 하나의 인스턴스이고, 각 상수가 enum 클래스의 생성자를 호출합니다. 1번째 스트링은 symbol에, 2번째 인자의 람다식은 DoubleBinaryOperator op에 대응이 되고, enum의 각 상수 인스턴스는 각각 symbol과 op를 가지고 있습니다.DoublueBinaryOperator는 (double 변수, double 변수) -> return double 변수 패턴의 함수형 인터페이스라고 생각하시면 되겠습니다. 
이 DoubleBinaryOperator에는 parameter들을 람다식에 대입하여 결과값을 double로 반환하는 applyAsDouble 메서드가 있습니다.
https://docs.oracle.com/javase/8/docs/api/java/util/function/DoubleBinaryOperator.html

설명이 불충분하시면 밑에 코멘트 남ㄱㅕ주세요.
