### ISSUE TITLE
[Effective Java] Item 44. 표준 함수형 인터페이스의 사용 이유??

### ISSUE THREAD

**Issue by taxol1203** [kjsu0209/JavaBook#30]
다음은 java.util.function의 기본 함수형 인터페이스들의 사용법입니다.  
```java
 @Test
    @DisplayName("표준함수형 인터페이스")
    void name2() {
        //
        UnaryOperator<Integer> unaryOperator = x->x+1;
        assertThat(unaryOperator.apply(1)).isEqualTo(2);
        //
        BinaryOperator<Integer> binaryOperator = (x,y)->x+y;
        assertThat(binaryOperator.apply(1,2)).isEqualTo(3);
        //
        Predicate<Integer> predicate = x-> x==1;
        assertThat(predicate.test(1)).isTrue();
        //
        Function<Integer,String> function = (x) -> String.valueOf(x);
        assertThat(function.apply(1)).isEqualTo("1");
        //
        Supplier<Integer> supplier = ()->1;
        assertThat(supplier.get()).isEqualTo(1);
        //
        Consumer<Integer> consumer = x ->{};   
    }
```
*출처 - 자바 봄   <https://javabom.tistory.com/86>*  

단도직입적으로..... 왜 쓰는 걸까요?  
단순히 저런 기능을 하는 메소드를 만들어 호출하는 것과 큰 차이가 있나요?

**Comment by daebalprime** [comment]
기존 자바에는 없던 lambda가 도입되면서 함수형 패러다임에 대한 지원을 시작했습니다.
싸피  자바스크립트 수업에서 다뤘었던 '함수는 일급객체'를 생각해본다면, Java에서도 함수형 프로그래밍 패러다임을 이용하여 간결하고 명확하게 코드를 작성할 수 있게 되었습니다.

ITEM 44에서 다뤘던 removeEldestEntry를 생각해본다면, java API의 구현에는 removeEldestEntry는 항상 false를 반환합니다. 즉 오래된 원소를 지우지 않는 것이 default입니다. 근데 항상 false만 리턴하라고 해당 메서드를 구현하지는 않았을 것이고, API User가 사용하라고 만든 메서드일 것입니다.
함수형 패러다임이 정착하기 전에는 LinkedHashMap을 상속받아 해당 메서드를 재정의하는 방법이 있을 것이지만 앞의 ITEM에서 다룬 것 처럼 위험하고 integrity를 깨뜨리기 쉬운 방법일 것입니다.
그러나 함수형 패러다임을 적용한다면, 어떤 조건을 만족했을 때 오래된 원소를 제거할 것인지 조건을 표현하는 람다식을 파라미터로 받도록 구현이 되어있었다면 복잡한 과정 없이 손쉽게 원하는 동작을 수정하고 구현할 수 있었을 것입니다.

함수형 프로그래밍 패러다임은 유용하다는 것을 받아들이셨다는 전제 하에, 함수형 인터페이스는 함수 객체의 type이라고 생각하시면 편할 것 같습니다. 올려주신 예제는 hello world 수준의 사용 예제일 뿐, 실무에서는 굉장한 생산성을 가져다 줄 상황을 많이 마주칠 것이라고 생각합니다.

설명 부족하면 코멘트 남겨주세요.
