### ISSUE TITLE
[Effective Java] Item 55. Optional 타입

### ISSUE THREAD

**Issue by kjsu0209** [kjsu0209/JavaBook#32]
Optional<T> 타입이 정확히 무엇인지 궁금합니다.
책 326p에서는 null이 아닌 T타입 참조를 담거나, 담지 않는다고 하는데, 그럼 T타입 or null을 담는다고 이해하면 될까요?

**Comment by jth2747** [comment]
네, Optional은 "null이 될 수도 있는 객체" 를 감싸는 래퍼 클래스고, 책에서 담지 않는다는 말은 null을 담는 다는 말입니다.  null을 담지만 null을 직접 다루지 않아도 되게 해주는 클래스입니다..

https://www.daleseo.com/java8-optional-after/
해당 링크에서 Optional 1부 2부 3부를 한번 슥 읽어보시는 것도 좋을 것 같습니다
