### ISSUE TITLE
[Effective Java] Item 52. 다중정의의 존재의의??

### ISSUE THREAD

**Issue by jth2747** [kjsu0209/JavaBook#33]
아이템 52에서 사용하지말라고 하고, 메소드 이름을 변경하여 사용하는 것을 권장하는데,
그렇다면 다중정의의 존재의의는 무엇일까요?

**Comment by daebalprime** [comment]
해당 아이템에서는 다중정의를 사용하지 말 것을 권고하고 있지만, 그 이유는 다중정의의 문제 자체라기 보다는, 다중정의 메서드 시그니쳐들 중  파라미터가 다른 overloading된 메서드의 파라미터와 위치가 같고 상속관계인 경우 발생하는 문제들에 집중하고 있습니다. 모든 다중정의를 죄악시하는 건 아닙니다.

StringTokenizer의 생성자의 경우, source String만을 받는 파라미터 1개짜리가 있고, String과 Delimiter(구분자)를 받는 파라미터 2개 짜리가 있습니다. 1개짜리의 경우 구분자는 white space로, 사람들이 많이 사용하는 기본값을 알아서 지정하는 생성자이며 만약 구분자를 바꾸고 싶다면 2개짜리를 사용하면 되며, 이게 제가 생각하는 다중정의의 훌륭한 예시가 아닐까 생각합니다. 

그리고 지난 아이템에서 가변인수를 설명하면서 최적화하는 부분에서도 다중정의를 설명하고 있습니다. 이펙티브 자바 내에서 소개하는 패턴에도, 자바 라이브러리 설계에도 다중정의는 잘 녹아 있습니다.

**Comment by kjsu0209** [comment]
다중정의(overloading)는 하나의 기능이 다양한 형태를 지원할 수 있게 해줍니다. 책에서는 이 지원하는 형태들이 반드시 분리되어야 한다고 나와 있어요. (ex. Collection과 ArrayList 둘 다 사용하면 혼란을 야기함)

예를 들어 draw()라는 메서드가 있고, 이 메서드가 float, int, double을 지원하고자 할 때, 다중정의를 쓰지 않으면 drawFloat, drawInt, drawDouble...등 메서드 이름이 많아집니다. 다중정의를 쓰면 draw라는 메서드 이름을 하나만 사용하게 되고, 파라미터로 세부 형태를 결정합니다. 그래서 추상 영역인 기능부분만 나타내어 메서드의 의미가 더 명확해진다고 봅니다.
