### ISSUE TITLE
[Effective Java] Item 61. 잘못 구현된 비교자

### ISSUE THREAD

**Issue by jth2747** [kjsu0209/JavaBook#39]
359 페이지의 비교자 예시 코드입니다.
`Comparator<Integer> naturalOrder = 
      (i, j) -> (i < j) ? -1 : (i == j ? 0: 1);`

이 코드를 사용하여 new Integer(42)와 new Integer(42)를 비교할 때 서로 다른 Integer 인스턴스라면 첫번째 값이 크게 나오기에 ==를 사용하면 안된다고 합니다. 그러면 ==를 사용했을 때 어떤 점 때문에 객체 비교시 첫번째 객체의 값이 크다고 판단하는 걸까요?

**Comment by taxol1203** [comment]
박싱된 기본 타입에 `==` 연산자를 사용하면 객체 참조의 식별성을 검사합니다.  
식별성이란 각 클래스의 주소를 비교한다고 저는 생각하였습니다.

코드 예제에서는 new Integer(42) 두 개를 비교하고 있는데, new 연산자를 통해 박싱된 기본 타입 클래스를 2개 생성하였기 때문에 주소가 다릅니다
따라서 `==`연산자를 사용하면 값은 42로 같아도 주소값이 달라 다른 값이라고 계산하여, false인 1을 반환합니다
따라서 첫번재 객체의 값이 크다고 판단하였다고 생각하였습니다.

**Comment by daebalprime** [comment]
어찌됐든 박싱된 기본 타입 또한 클래스의 인스턴스입니다. new String("a") != new String("a")가 같지 않은 것과 같습니다.
