### ISSUE TITLE
Item7. 38p "참조를 담은 변수를 유효 범위(scope) 밖으로 밀어내는 것"

### ISSUE THREAD

**Issue by taxol1203** [kjsu0209/JavaBook#4]
주어진 Stack 예제에서 pop method의 메모리 누수를 방지하기 위해,  
```java
public Object pop(){
  if(size == 0)
    throw new EmptyStackException();
  Object result = elements[--size];
  elements[size] = null;    // 다 쓴 참조 해제
  return result;
}
```
으로 size 범위를 벗어난 객체를 null 처리를 하였습니다.  

```
다 쓴 참조를 해제하는 가장 좋은 방법은 그 참조를 담은 변수를 유효 범위(scope) 밖으로 밀어내는 것이다.  
여러분이 변수의 범위를 최소가 되게 정의했다면(item 57) 이 일은 자연스럽게 이뤄진다.  
```
라는 내용이 그 이후에 나오는데, null처리가 아닌, 참조를 담은 변수를 유효 범위 밖으로 밀어낸다는 것이 잘 이해가 되질 않네요, 혹시 이 부분을 어떻게 이해하셨는지 의견 부탁드려용😙

**Comment by kjsu0209** [comment]
변수의 **유효 범위(scope)**란 변수를 사용할 수 있는 범위입니다. 
null 처리로 직접 원래 변수에 저장된 레퍼런스 객체에 접근하지 못하게 할 수도 있지만,
아래 코드와 같이 변수를 처음 사용할 때 선언해 유효 범위를 벗어나면 GC 대상이 되게 할 수 있다고 합니다.
```
int a = 1;
{
    int b = 2;
   // 블록 안에서는 a, b의 유효 범위 안에 들어감. 둘 다 접근 가능.
}
// 블록 밖으로 나가면 b의 유효 범위 밖으로 나갔기 때문에 접근 불가능(GC 대상)
```

근데 유효범위 밖으로 밀어내는 게 좋은 방법이지만 Stack에는 적용이 어려울 것 같아요. 클래스 내부의 멤버가 아닌 인스턴스 객체를 대상으로 쓰는 방법을 소개한 것 같습니다..🤔

**Comment by daebalprime** [comment]
제가 이해한 유효범위는...
스택을 어레이로 담고 있는데, 예를 들어 사이즈가 16이라고 하면 인덱스가 0~15 내의 값들만 의미가 있겠죠.
책 안에서 저 코드 이전에 소개된 문제가 되는 코드에서, 16번 인덱스 이후의 객체들 레퍼런스 값이 남아있기 떄문에 '유효 범위'라는 말을 쓴 것 같습니다.
