### ISSUE TITLE
[Effective Java] Item 70. 비 검사 예외는 프로그램에서 잡을 필요가 없다?

### ISSUE THREAD

**Issue by taxol1203** [kjsu0209/JavaBook#41]
예외(Exception)은 검사 예외(Checked Exception)과 비 검사 예외(Unchecked Exception)으로 구분할 수 있는데  
RuntimeException을 상속하지 않는 클래스는 `검사 예외`, 반대로 상속한 클래스는 `비 검사 예외`로 분류할 수 있다고 합니다.  

자바 수업을 배우거나 코드를 보면 예외가 일어나면 보통 try catch로 예외를 잡는 법을 배웁니다.  
저희가 배운 이런 try catch 작업은 검사 예외를 사용하여 **호출하는 쪽에서 복구**를 하는 것이라고 생각하면 되는 건가요?

또한 *비검사 throwable은  프로그램에서 잡을 필요가 없다.* 라는 것은 try catch로 예외를 잡을 필요가 없다라는 뜻인지 궁금합니다

**Comment by daebalprime** [comment]
책에서 제시하는 대안들은 모두 API를 만드는 프로그래머의 시점에서 서술합니다.

1.try catch 작업은 검사 예외를 사용하여 호출하는 쪽에서 복구를 하는 것이라고 생각하면 되는 건가요?
맞습니다. 예를 들어 movie 프로젝트를 생각해볼 때, 영화 ID를 pk로 잡아놓았는데 이미 존재하는 영화 ID를 또 삽입하려고 시도하면 SQLIntegrityConstraintViolationException을 띄울 것인데 해당 예외가 발생한다 하여 프로그램이 종료되는 일은 없어야 할 것이고 적당한 예외처리를 통해 사용자에게 "이미 존재하는 키입니다" 와 같은 예외를 띄워주는 방향이 올바르다고 생각합니다.

2. 또한 비검사 throwable은 프로그램에서 잡을 필요가 없다. 라는 것은 try catch로 예외를 잡을 필요가 없다라는 뜻인지 궁금합니다
비검사 throwable은 복구 가능한 상황이 아닌 프로그램 자체의 문제임을 암시하기 때문에 try-catch로 예외 처리를 하는게 아닌 프로그램의 논리적 오류를 수정하여야 합니다.

**Comment by kjsu0209** [comment]
```저희가 배운 이런 try catch 작업은 검사 예외를 사용하여 호출하는 쪽에서 복구를 하는 것이라고 생각하면 되는 건가요?```
=> 네. API에서는 검사 예외가 발생했을 경우 처리(복구)하는 방법이 따로 구현되어 있지 않습니다. 검사 예외는 시스템에 치명적이지 않은 문제를 미리 대비하라는 의미에 가까운 것 같아요.

```또한 비검사 throwable은 프로그램에서 잡을 필요가 없다. 라는 것은 try catch로 예외를 잡을 필요가 없다라는 뜻인지 궁금합니다```
=> try catch를 쓴다는 말은 해당 예외가 발생해도 적절한 복구 작업을 할 경우 시스템이 문제 없이 작동된다는 뜻입니다. 
비검사 예외는 프로그램 자체의 문제이기 때문에 복구가 불가능하거나, 하더라도 득보다 실이 많다고 합니다.

**Comment by kjsu0209** [comment]
![image](https://user-images.githubusercontent.com/35682236/115998676-59777800-a623-11eb-86c4-3cc14f7c25ff.png)

위 이미지 보시면 빨간색 예외보다 초록색 예외가 더 JVM과 가깝고, 발생 시 시스템에 치명적입니다.
