### ISSUE TITLE
[Effective Java] Item 72. 표준 예외를 재사용 하는 법

### ISSUE THREAD

**Issue by kjsu0209** [kjsu0209/JavaBook#42]
Item 72에서는 ```IllegalArgumentException```이나 ```ConcurrentModificationException```, ```UnsupportedOperationException```이 많이 재사용 된다고 합니다.
여기서 재사용이라는 말이 말그대로 갖다 쓰는 것을 의미하는지, 클래스를 하나 만들어서 위 예외를 상속 받게 한 후 커스텀 하는 건지 궁금합니다.

**Comment by daebalprime** [comment]
의미와 맥락이 일치하는 곳에 이미 존재하는 예외를 재사용하라는 의미입니다.
