### ISSUE TITLE
[Effective Java] Item 82. 스레드 안전성 수준별 차이

### ISSUE THREAD

**Issue by kjsu0209** [kjsu0209/JavaBook#47]
조건부 스레드 안전과 스레드 안전하지 않음은 모든 메서드를 외부에서 동기화해주는지에 따라 나뉜다고 이해하면 될까요?
메서드가 1개 있을 때, 이 메서드를 외부에서 동기화 해주어야 하면 NonThreadSafe이고, 메서드가 4개 있을 때, 3개의 메서드를 외부에서 동기화 해주어야 하면 Conditional ThreadSafe인건가요?

외부에서 동기화를 해주어야 하는 것 자체가 Thread Safe하지 않다고 생각하는데 헷갈립니다 😞

**Comment by daebalprime** [comment]
동기화를 위해 치러야 할 비용이 있기 때문에, '특정 메서드에만 동기화로 쓰레드 안전을 보장할 수 있음'을 알려주기 위해 조건부 쓰레드 안전 레벨이 존재하는 것 같습니다.

말장난을 좀 더 파고들면, conditionally thread safe하다는 말은 어떤 조건에선 not-thread safe하다는 의미기도 합니다.
