### ISSUE TITLE
[Effective Java] Item 81. Pharser

### ISSUE THREAD

**Issue by kjsu0209** [kjsu0209/JavaBook#48]
Item 81에서 동기화 장치 중 가장 강력한 게 ```Pharser```라고 나와 있는데, Pharser가 정확히 뭘까요?
간단히 CountDownLatch 여러 개를 합친 걸로 이해하면 될까요?

**Comment by taxol1203** [comment]
Pharser는 동기화에 참여할 스레드의 수가 동적이고 재사용이 가능하도록 만든 동기화 장치 중 하나입니다

[Java concurrent 패키지의 동기화 장치](https://javabom.tistory.com/35)에 의하면 
동기화 장치에 대하여 자세한 설명이 되어있습니다. 여기서 참고하시면 될 것 같습니다!
