### ISSUE TITLE
[Effective Java] Item 10. "인스턴스의 논리적 동치성"

### ISSUE THREAD

**Issue by taxol1203** [kjsu0209/JavaBook#5]
논리적 동치성이란 
```
합성명제 p와 q의 진릿값이 서로 같은 경우를 말합니다. 기호로는 p ≡ q 로 표시하며, "p와 q는 같다" 또는 "p와 q의 진릿값은 같다"라고 읽습니다. 
```
라고 뜻합니다.  
그렇다면 `인스턴스의 논리적 동치성을 검사` 한다는게 잘 이해가 되질 않네요  
혹시 인스턴스의 필드에 있는 값들이 서로 다 같다는 것을 뜻하는 건가요?

**Comment by daebalprime** [comment]
> 혹시 인스턴스의 필드에 있는 값들이 서로 다 같다는 것을 뜻하는 건가요?

그럴 수도 아닐 수도 있습니다. 논리적 동치성과 모든 필드값의 동일성은 관련이 없습니다. 마땅한 예가 떠오르지 않아서 지저분하지만 직접 생각해낸 예를 들어보겠습니다. 
어떤 미로 시뮬레이션 알고리즘을 푼다고 가정합시다.  움직이는 모든 객체를 MovingObject로 정의하고   이 움직이는 물체가 어떤 종류인지 정의하는 String type (예를 들어 "쥐", "사람", "외계인" 등등), 그리고 좌표 int x, int y를 구현할 것입니다. 이 문제는 같은 종류의 움직이는 물체 중 어느 하나가 먼저 미로를 탈출하면 나머지 같은 종류의 MovingObject를 다 죽인다는 무시무시한 문제입니다. 
만약 어떤 MovingObject가 탈출했을 때,  미로 내에 존재하는 모든 MovingObject를 순회하여 같은 종류의 인스턴스를 모두 지워버리는 구현을 하여야 합니다. 이 때 두 물체가 같음을 어떻게 판단할 수 있을까요? 좌표가 같으면 같은 종류의 인스턴스일까요? 
type이 같다면 논리적으로 '같다고' 할 수 있지 않을까요? 이 때 좌표가 같을 수도, 같지 않을 수도 있지만 확실한건 type 필드의 값은 동일할 것입니다.

쓰다보니 무슨 글인지 모르겠습니다. 나중에 더 좋은 예시나 설명을 찾게 되면 올리겠습니다.

**Comment by kjsu0209** [comment]
인스턴스의 논리적 동치성을 검사한다는 말은 두 인스턴스가 같은지 확인할 때 물리 저장소 주소(hashCode)로 비교하는 것이 아닌 어떤 논리적인 규칙으로 비교한다는 것으로 이해됩니다.

예를 들어 Integer 객체가 두 개 있을 때, 두 객체의 값이 2로 같더라도 물리 저장소 주소로만 비교하면 다르다고 나옵니다. 
Integer 객체가 정수를 객체로 표현한 것이니 자바에서 Integer 객체 인스턴스들을 비교할 때 두 객체의 정수 값으로 비교하는 규칙을 equals 메서드에 재정의한 것으로 이해하면 될 것 같습니다. 

그래서 객체의 목적에 따라 인스턴스들의 모든 멤버 필드가 같아야 한다는 규칙을 넣을 수도 있고, String처럼 문자열 안의 문자를 기준으로 비교하는 규칙을 넣을 수도 있습니다.
