### ISSUE TITLE
[Effective Java] Item 83. 지연 초기화 홀더 클래스 (lazy initialization holder class)

### ISSUE THREAD

**Issue by jth2747** [kjsu0209/JavaBook#50]
442 페이지의 2번째 문단 2~3번째 줄에서는 

> 지연 초기화를 사용 할 시 클래스 혹은 인스턴스 생성 시의 초기화 비용은 줄지만 그 대신 지연 초기화하는 필드에 접근하는 비용은 커진다.

라고 되어 있습니다. 그러나 443 페이지의 지연 초기화 홀더 클래스의 설명 중 마지막 문단 마지막 줄부터는

> ...클래스를 초기화할 때만 필드 접근을 동기화 하고 초기화 끝난 후에는 검사나 동기화 없이 필드에 접근한다...

라고 되어있는데 지연 초기화의 개념과 반대되는 의미가 아닐까요. 제가 잘못 이해한 걸까요?

**Comment by taxol1203** [comment]
제 생각에는 
> ...클래스를 초기화할 때만 필드 접근을 동기화 하고
라는 뜻이 지연 초기화를 하여, 해당 필드를 처음 사용할 때, 초기화를 하는데 그때 초기화 할 때만 접근을 동기화 한다는 뜻이라고 이해하였습니다!
