### ISSUE TITLE
[Effective Java] Item 86. Serializable 클래스를 상속 받은 클래스에게 주어진 부담

### ISSUE THREAD

**Issue by taxol1203** [kjsu0209/JavaBook#53]
457p.  2번째 문단에서  다음과 같은 내용이 있습니다.
> Serializable를 구현한 상속용으로 설계된 클래스(인터페이스)를 확장하거나 구현한 클래스는 커다란 부담을 지우게 된다.  

여기서 커다란 부담이란 것은 무엇을 뜻하는 것 일까요?

**Comment by kjsu0209** [comment]
간단히 생각하자면, Serializable을 구현한 클래스를 설계할 때 직렬화, 안정성 문제 등 고려해야 할게 많습니다. 그럼 Serializable을 구현한 클래스나 인터페이스를 한 번 더 구현한 클래스도 똑같은 부분을 고려하여 설계해야 하니 책에서 이를 커다란 부담이라고 하는 것 같습니다.
