### ISSUE TITLE
[Effective Java] Item 87. JVM을 실행 할 때마다 값이 달라지는 long 필드

### ISSUE THREAD

**Issue by taxol1203** [kjsu0209/JavaBook#55]
464p의 2번째 문단에서, 
> JVM을 실행할 때마다 값이 달라지는 필드도 마찬가지인데, 네이티브 자료구조를 가리키는 long 필드가 여기에 속한다.  

라고 되어있습니다. Primitive type인 long 필드가 JVM을 실행할 때 마다 값이 달라진다는 것이 무슨 뜻일까요?
long 필드를 표현하기 위한 내부 구현 방법이 달라진다는 것일까요?

**Comment by jth2747** [comment]
원문에서는 네이티브 구조를 가리키는 포인터라고 언급되어 있는데,

> It also includes fields whose values are tied to
one particular run of the JVM, such as a long field representing a **pointer** to a
native data structure.

JNI관련 개념인 것 같은데, 자바 필드에 네이티브 구조에 대한 포인터를 저장할 때 int가 아닌 long 필드를 사용한다고 합니다. 포인터이기 때문에 실행때마다 값이 달라진다는 것 아닐까요..

저도 이 부분은 이해가 안되서 찾아봤는데 언급도 잘 안되고 도움을 줄만한 자료를 못찾겠네요 ㅠㅠ 이해가 되신 분들 답변 보충해주시면 감사드리겠습니다
