### ISSUE TITLE
[Effective Java] Item 87. 직렬 버전 UID의 목적

### ISSUE THREAD

**Issue by kjsu0209** [kjsu0209/JavaBook#56]
직렬 버전 UID가 호환성 문제를 해결하기 위해서만 존재하나요?
다른 용도가 있는지 궁금합니다.

**Comment by taxol1203** [comment]
넵, serialVersionUID는 예상하신 것 처럼, 직렬화와 역직렬화를 하는 시점의 클래스에 대한 버전 번호를 부여하여, 역 직렬화 중에서 직렬화된 개체의 송신자와 수신자가 직렬화와 관련하여 호환되는 해당 개체의 클래스를 로드했는지 확인하는 용도로만 사용되는 것 같습니다.
