### ISSUE TITLE
[Effective Java] Item 10. 표준형(canonical from)이 무슨 말일까요

### ISSUE THREAD

**Issue by kjsu0209** [kjsu0209/JavaBook#6]
> (전략) ... 비교하기가 아주 복잡한 필드를 가진 클래스도 있다.
> 이럴 때는 그 필드의 <b>표준형</b>을 저장해둔 후 표준형끼리 비교하면 훨씬 경제적이다. (후략)
> (63p. 4번째 단락. Effective Java)

여기서 표준형(canonical from)이 무슨 말일까요

**Comment by daebalprime** [comment]
파일의 경로를 예로 들자면, context에 종속되어 global하게 파일을 특정지을 수 없는 경로들이 있습니다. 가장 대표적인 예로 상대경로가 있습니다. 만약 두 파일이 같은 파일인지 확인하고 싶다고 가정했을 때, 바탕 화면 폴더 시점에서 본 상대 경로와 C드라이브 루트 폴더 시점에서 본 상대경로가 같은 파일을 가르킨다고 하더라도 context(상대 경로의 root)를 고려하여 비교하여야 하는 복잡한 과정이 뒷받침되어야 합니다.

그 대신 절대 경로를 이용한다면, 그냥 파일의 경로 string이 같은 지만 비교하면 되기 때문에 편리할 것입니다. 절대 경로가 파일 경로의 canonical form이라고 할 수 있을 것입니다.


스택오버플로우에 같은 질문이 있으니 자세한 것은 아래를 참조하시기 바랍니다.
https://stackoverflow.com/questions/280107/what-does-the-term-canonical-form-or-canonical-representation-in-java-mean/11047738
