### ISSUE TITLE
[Effective Java] Item 11. 지연 초기화할 때 스레드 안정성을 고려해야 하는 이유

### ISSUE THREAD

**Issue by kjsu0209** [kjsu0209/JavaBook#7]
71p에서 지연 초기화 전략을 쓰면 hashCode가 처음 불릴 때 해시코드를 계산해준다고 나옵니다.
단순하게 생각하면 boolean값을 써도 충분히 구현할 수 있을 것 같은데,
지연 초기화할 때 스레드 안정성을 고려해야 하는 이유가 뭘까요?

**Comment by daebalprime** [comment]
자세하게 찾아본 것은 아니라서 뇌피셜로 답해드리겠습니다(추후 아이템에서 다룰 주제이기 때문에 이해하기가 어려웠습니다.)
지연 초기화의 목적은 사용할지 않을지도 모를 hashCode값을 인스턴스시에 생성하면 낭비가 되지 않을까? 에서 시작한 아이디어입니다. 인스턴스 생성 시 hashCode를 계산한다면 그 인스턴스에 대해서는 딱 1번 호출되겠죠.
만약 hashCode를 수행하는 값이 비싸다면(3초 이상으로 잡아봅시다), 만약 0초일 때 같은 인스턴스에 대해 1번 쓰레드가 hashCode()를 호출하여 계산을 수행하는 와중에, 2번 쓰레드가 hashCode()를 1.5초에 호출한다면, 총 2번 수행하게 되겠죠. 이렇게 된다면 성능 최적화를 위해 택한 지연 초기화의 의미도 퇴색되고, 의도하지 않은 행동이기도 할 것입니다.
