### ISSUE TITLE
[Effective Java] Item 15. 불변식을 보장할 수 없다??

### ISSUE THREAD

**Issue by taxol1203** [kjsu0209/JavaBook#8]
99페이지 두 번째 단락을 보시면,   
```가변 객체나, final이 아닌 인스턴스 필드를 public으로 선언하면, 불변식을 보장할 수 없다. ```  
라고 되어있습니다.  
불변식을 깨뜨린 다는건, 다른 객체에서 임의로 값을 변경이 가능하다는 뜻일까요?
이에 따른 예제 코드를 작성하였는데, 위에 해당하는 내용과 일치하는지 확인 부탁드립니다.  
```java
public static class C {
  // 가변 인스턴스
  public int[] arr = {1,2,3,4,5};
  public char ch = 'c';
  // 가변 객체
  public List<Integer> list = new ArrayList<Integer>();
}

public static class D {
  C c = new C();
  
  public void changeC() {
    // 객체 C의 불변성 보장 실패
    c.arr[3] = 6;
    c.ch = 'd';
    c.list.add(11);
  }
}
```

**Comment by jth2747** [comment]
네, 올려주신 코드같은 경우가 인스턴스 필드가 public으로 선언이 되어 있어 다른 클래스에서 인스턴스를 계속 수정 가능하기에 '불변식'이라는게 보장되지 않는다의 알맞은 예시인 것 같습니다.

추가로 thread-unsafe에 대해 한 번 말해보자면, 인스턴스 변수는 힙에 할당되며 공유자원입니다. 즉, 모든 스레드가 이 공유자원에 접근 할 수 있습니다. public 가변 필드를 갖는 클래스는 스레드 처리중인 객체에 수정을 위해 자꾸 접근을 할텐데 그런 식으로 객체의 내부값이 돌발적으로 변화하거나, 의도하지 않았더라도 수정되는 시도가 생기면 스레드 자체가 붕괴할 위험이 있습니다. 
따라서 불변식이 보장되지 않아 값을 외부에서 계속 수정 가능하다 라는 것은 thread-unsafe 할 수 밖에 없습니다.

불변식의 개념을 설명해준 링크인데 그냥 한번 보시면 좋을 것 같습니다.
https://stackoverflow.com/questions/8902331/what-is-a-class-invariant-in-java
