### ISSUE TITLE
[Effective Java] Item 17. 함수형 프로그래밍이란?

### ISSUE THREAD

**Issue by kjsu0209** [kjsu0209/JavaBook#9]
함수형 프로그래밍은 피연산자에 함수를 적용해 결과를 반환하지만 피연산자 자체는 그대로인 프로그래밍 패턴이라고 합니다.
```
public int method(int num){
    return num+1;
}
```
위 함수처럼 파라미터로 num을 넘기고 num을 변경하지 않고 결과를 반환하면 함수형 프로그래밍이라고 하나요?

**Comment by taxol1203** [comment]
[함수형 프로그래밍에 대한 post](https://medium.com/humanscape-tech/%ED%95%A8%EC%88%98%ED%98%95-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D%EC%97%90-%EA%B4%80%ED%95%B4-7f6172599fc)에 따르면 함수형 프로그래밍에서는 
* 불변성 (Immutable)
* 참조 투명성 (Referential Transparency)
* 일급 함수 (First-class Function)
* 게으른 평가 (Lazy Evaluation)  
의 4가지 특성이 있다고 합니다.  
일단 불변성의 특성을 지키니 함수형 프로그래밍의 조건에 부합하여 맞을꺼라는 생각을 합니다

**Comment by jth2747** [comment]
함수형 프로그래밍의 개념을 살펴보면,

> 함수형 프로그래밍은 계산을 수학적 함수의 조합으로 생각하는 방식을 말한다. 이것은 일반적인 프로그래밍 언어에서 함수가 특정 동작을 수행하는 역할을 담당하는 것과는 반대되는 개념으로, **함수를 수행해도 함수 외부의 값이 변경될 수 없다**.

> 피연산자에 함수를 적용해 그 결과를 반환하지만, **피연산자 자체는 그대로**인 프로그래밍 패턴을 함수형 프로그래밍이라 한다.

올려주신 코드에서 num을 파라미터로 받고 num을 포함한 함수(수식)을 return하지만 num의 값 자체가 바뀌는 것은 아니기에 함수형 프로그래밍이라고 할 수 있을 것입니다.
